### PR TITLE
YAML and JSON support

### PR DESCRIPTION
**Pull request by siddharthist**
* Import/export JSON/YAML
* Deprecation warnings and upgrade paths!
  - Add CHANGELOG with migration instructions

### CODE REVIEW

**Comment by siddharthist** [comment]
cc @JackKiefer 

You may want to try pulling this branch, building, and upgrading your recipes to the new format :smile:

**Comment by JackKiefer** [comment]
Ah, yes! I will do this today :)

**Comment by JackKiefer** [comment]
Thank you!!!

**Comment by siddharthist** [comment]
@JackKiefer Did you have time to check this out? I know that such things have a tendency to get away... :smile:

**Comment by JackKiefer** [comment]
@siddharthist I did not do this on that day :sweat_smile: 
I'm rather swamped with the semester...

**Comment by siddharthist** [comment]
Ping @JackKiefer

**Comment by JackKiefer** [comment]
Wow! I checked this out and it looks amazing!!

**Pull request merged**
