### PR TITLE
Conform to the XDG specification

### PR DESCRIPTION
**Pull request by siddharthist**
Partially addresses #61, but I think it's a good idea in general. 

This isn't quite complete: it doesn't currently copy in default configurations (which means that `herms` just crashes, even with commands like `datadir` - not very helpful!). I wanted to see if you're interested before polishing everything off.

### CODE REVIEW

**Comment by JackKiefer** [comment]
Ah, yes, I quite like this idea! Please do finish polishing :)

**Comment by siddharthist** [comment]
@JackKiefer Great! Is there anything you'd like to see changed except for copying in default configurations?

**Comment by JackKiefer** [comment]
Nothing that I can think of!

**Comment by siddharthist** [comment]
@JackKiefer Done!

**Pull request merged**
