### PR TITLE
Update brick

### LINKED ISSUE #80: Failing Travis builds
It seems that a new version of the Brick library breaks our CI builds: https://travis-ci.org/JackKiefer/herms

### PR DESCRIPTION
**Pull request by jeremystucki**
Does this pull request address a current issue or idea in Contributing.md?
Resolves #80

Tell us what you did!
I bumped the version of the brick dependency

Do you have any questions? :)
No

### CODE REVIEW

**Comment by jeremystucki** [comment]
Could someone restart [this](https://travis-ci.org/JackKiefer/herms/jobs/440107056) step?
This was working just a few minutes ago [on my fork](https://travis-ci.org/jeremystucki/herms/builds/440101354?utm_source=github_status&utm_medium=notification).

**Comment by siddharthist** [comment]
@JackKiefer could restart the build.

As an alternative, I think you can just close and re-open this PR.

Thanks for the contribution, this is definitely needed!!

**Comment by siddharthist** [comment]
Oh, just kidding, I was able to restart it :smile:

**Comment by siddharthist** [comment]
It does appear that the build reliably fails on GHC 8.0.2. Now that GHC 8.6 is out, we might consider dropping support for it.

**Comment by mauriciofierrom** [comment]
It seems to be an out-of-memory issue. 

out_of_memory

We could try running

`cabal new-build ...`

with only one job (-j1) so it passes and caches the dependencies, and then restore the two jobs in the travis file. WDYT? @jeremystucki @siddharthist

**Comment by siddharthist** [comment]
@mauriciofierrom Thanks! Feel free to open a PR for moving it back to `j2`.

**Pull request merged**
